#ifndef DONUT_APPLICATION_EVENT_HPP
#define DONUT_APPLICATION_EVENT_HPP

union SDL_Event;

namespace donut {
namespace application {

/**
 * Opaque handle to a data structure containing information about an Application
 * event.
 *
 * Instances of this type are generated by an Application when certain events
 * occur in the application environment, typically as a result of user input.
 * These events should mainly be forwarded to subsystems such as an InputManager
 * for processing and do not need to be manually handled.
 */
using Event = SDL_Event;

} // namespace application
} // namespace donut

#endif
